name: Android Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  release:
    types: [published]

env:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        cache-write-only: ${{ github.ref != 'refs/heads/main' }}

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build APKs and AAB
      run: |
        ./gradlew assembleDebug assembleRelease bundleRelease

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: CodeEditor-Debug
        path: app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30

    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: CodeEditor-Release
        path: app/build/outputs/apk/release/app-release.apk
        retention-days: 30

    - name: Upload App Bundle
      uses: actions/upload-artifact@v4
      with:
        name: CodeEditor-Bundle
        path: app/build/outputs/bundle/release/app-release.aab
        retention-days: 30

    - name: Upload Mapping File (Release)
      if: github.event_name == 'release'
      uses: actions/upload-artifact@v4
      with:
        name: mapping-file
        path: app/build/outputs/mapping/release/mapping.txt
        retention-days: 30
