name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Build Release APK
      run: |
        chmod +x ./gradlew
        ./gradlew assembleRelease
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          app/build/outputs/apk/release/app-release.apk
          app/build/outputs/bundle/release/app-release.aab
        body: |
          ## 📱 CodeEditor Mobile
          
          ### Novidades nesta versão:
          - Editor de código móvel
          - Suporte a JavaScript, Python, HTML, CSS
          - Interface moderna
          - 100% offline
          
          ### 📥 Download:
          - **APK**: `app-release.apk` (Instalar no Android)
          - **AAB**: `app-release.aab` (Upload na Play Store)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
